### ISSUE TITLE
Filtering on an exact purl in API take over 1min

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/vulnerablecode#1415]
Looking for an exact purl can take over 1 minute to render. That's a major usability issue.
https://public.vulnerablecode.io/api/packages/?purl=pkg:pypi/django@1.4.9

**Comment by TG1999** [comment]
It's not a nexact purl problem, also happens with https://public.vulnerablecode.io/api/packages?type=pypi&name=django, this is due to the large volume of data and the many operations done to get django data in the background. Opened a ticket here https://github.com/nexB/vulnerablecode/issues/1416

**Comment by pombredanne** [comment]
It is faster but still takes about 10 to 15 seconds and is not fast enough

**Comment by TG1999** [comment]
Please look at https://github.com/aboutcode-org/vulnerablecode/issues/1572 on what we did to tackle this issue
