### ISSUE TITLE
Collect CVE tagged with CERTCC fork of Metasploit Framework

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/vulnerablecode#1455]
See https://github.com/CERTCC/metasploit-framework and https://github.com/certcc/metasploit-framework/tags 

CERT/CC's fork of Metasploit Framework in which we are tagging commits that include vulnerability IDs. The first commit for an ID we recognize gets the tag for that ID. Aside from adding git tags, we do not otherwise modify the code. Updates hourly. 

See discussion document at https://docs.google.com/document/d/1XtMmxthmANhr-IqXsyMgFnrOq5fTGfsE/edit?usp=sharing&ouid=117241222429542576816&rtpof=true&sd=true
See work-in-progress normalized model spreadsheet at https://docs.google.com/spreadsheets/d/1J2t2T_s015pnAouy5ss-AA0SI4e2xjT4uICjlL_Aa38/edit?usp=sharing

**Comment by ziadhany** [comment]
@pombredanne According to my understanding, the Metasploit framework stores all vulnerability data in `modules_metadata_base.json`. After comparing the two files, I believe we should close this issue, as the data is identical. Please let me know if there are any differences between the two repositories that we need to import.

closed by #1562

https://github.com/rapid7/metasploit-framework/blob/master/db/modules_metadata_base.json
https://github.com/CERTCC/metasploit-framework/blob/master/db/modules_metadata_base.json

```
ziad-hany@ziad-hany:~/Downloads/test$ sha256sum CERTCC_modules_metadata_base.json 
f7798f168a451acb31c74f762c75d753848bea89b55ee7f05efbf37d434a999a  CERTCC_modules_metadata_base.json
ziad-hany@ziad-hany:~/Downloads/test$ sha256sum rapid7_modules_metadata_base.json 
f7798f168a451acb31c74f762c75d753848bea89b55ee7f05efbf37d434a999a  rapid7_modules_metadata_base.json

```
