### ISSUE TITLE
VCIO-next: API performance issues  (packages endpoints)

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/vulnerablecode#1538]
Let's focus on the Package-related endpoints for now as those are the ones used to collect vulnerability data in DejaCode.

Those tests were run on a clean install of VCIO with only the `nginx.NginxImporter` data set.
```
Package.objects.all().count()  # 88
Vulnerability.objects.count()  # 39
```

It's a very small amount of data but somehow looking at a single Package triggers over a thousand queries.

- Package list `/api/packages/` (on only 88 packages) -> **6,124 queries**: 5706 similar queries.  Duplicated 73 times.
- Package details `/api/packages/63` -> **1,329 queries**: 1230 similar queries.  Duplicated 16 times.
- Bulk search `/api/packages/bulk_search` (providing the 88 purl): **39,925** queries.

This is quite problematic in the context of batch data collection using the VCIO API.
The `PackageSerializer` and related QuerySets require optimization.
Once done, make sure to implement unit test using the `assertNumQueries` to make sure that future code change do not add uncontrolled queries back.

Related issues:
- https://github.com/aboutcode-org/vulnerablecode/issues/1492
- https://github.com/aboutcode-org/dejacode/issues/94#issuecomment-2298445423 
- https://github.com/aboutcode-org/vulnerablecode/issues/1549

For bulk lookup, we track this here:
- [ ] #1561

**Comment by pombredanne** [comment]
First batch of improvements went in with this PR:
- https://github.com/aboutcode-org/vulnerablecode/pull/1547

More to come

**Comment by pombredanne** [comment]
The performance is now acceptable. We need to9 make sure we save a baseline of performances.

**Comment by pombredanne** [comment]
FYI, the key code to get this fixed is the new API design in #1572

**Comment by pombredanne** [comment]
@tdruez @TG1999 is this completed and closable? If yes, please do!

**Comment by tdruez** [comment]
@TG1999 I've run some data collection using the previous and the new implementation (api v1).

Fetching for 133485 Packages, using bulk_search, with 100 PURL entries per request, so about 1,334 HTTP requests total

- Previous: Completed in 39.5 minutes
- New: Completed in 21.0 minutes

Seems like we double the performance on the package endpoint.
