### ISSUE TITLE
BUG: The /api/cpes endpoint raises a 500

### ISSUE THREAD

**Issue by tdruez** [aboutcode-org/vulnerablecode#1557]
https://public.vulnerablecode.io/api/cpes -> Server Error (500)

**Comment by AryanSwaroop** [comment]
Am I work on this issue ?

**Comment by pombredanne** [comment]
@AryanSwaroop sure, you are welcomed.

**Comment by pombredanne** [comment]
@AryanSwaroop actually, @TG1999 is on it.
