### ISSUE TITLE
No vulnerabilities found for Go packages / Percent-Encoding in purl

### ISSUE THREAD

**Issue by wkl3nk** [aboutcode-org/vulnerablecode#1620]
Hello,

I use ORT 34.0.0 in combination with VulnerableCode.
The _GoMod_ ORT package analzyer returned a dependency:

```
id: "Go::github.com/quic-go/quic-go:0.40.0"
purl: "pkg:golang/github.com%2Fquic-go%2Fquic-go@0.40.0"
```

On first sight, the purl looks strange, because it has both the slash character "/" and the percent-encoded equivalent of the "/" which is "%2F".

I think ORT is correct in the purl, because [the purl specification](https://github.com/package-url/purl-spec/blob/master/PURL-SPECIFICATION.rst#rules-for-each-purl-component) states:

* namespace: Each namespace segment must be a percent-encoded string
* name: A name must be a percent-encoded string

I think we don't have a namespace here (See the `id`: "Go::gith..."
And the name is _github.com%2Fquic-go%2Fquic-go_
So name is completely percent-encoded. Correct???

The problem: When I do a bulk-search using the VulnerableCode API, I get **no** vulnerability records reported, although this component definitely **has** vulnerability records.

Can you please make a statement about usage of percent-encoding in purls and if this is supported in the API?
What advice are you giving me?
Will you fix it on **your** side?

Reference to ORT issue: https://github.com/oss-review-toolkit/ort/issues/9298

**Comment by sschuberth** [comment]
FYI, the [*golang* examples](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#golang) also have no encoded slashes, and there generally seems to be some [confusion about what is right](https://github.com/package-url/purl-spec/pull/176).

**Comment by keshav-space** [comment]
@wkl3nk at the moment we don't encode the paths in the golang PURL. If you instead search for `pkg:golang/github.com/quic-go/quic-go@0.40.0`, you will get the vulnerabilities here https://public.vulnerablecode.io/packages/search. 

VulnerableCode is using https://github.com/package-url/packageurl-python for handling PURLs and with respect to golang it treats the last segment as the name and the rest as the namespace. So, for `pkg:golang/github.com/quic-go/quic-go@0.40.0`, packageurl-python interprets:
- **namespace:** github.com/quic-go
- **name:** quic-go

Another example `pkg:golang/github.com/go-jose/go-jose/v3@3.1.0` in this case:
- **namespace:** github.com/go-jose/go-jose
- **name:** v3


> FYI, the [_golang_ examples](https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#golang) also have no encoded slashes, and there generally seems to be some [confusion about what is right](https://github.com/package-url/purl-spec/pull/176).

Yes, there is some confusion regarding the handling of golang PURLs. We need to add proper guidelines on handling golang PURLs here https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#golang.

**Comment by johnmhoran** [comment]
@wkl3nk @keshav-space I've added a comment re my interpretation of encoding slashes and in particular the `go` PURL `pkg:golang/github.com%2Fquic-go%2Fquic-go@0.40.0` to one of the open PRs in the purl-spec repo -- see https://github.com/package-url/purl-spec/pull/176#issuecomment-2429868273

**Comment by johnmhoran** [comment]
Update:  other members of the community have promptly expressed disagreement with my interpretation -- 

- https://github.com/package-url/purl-spec/pull/176#issuecomment-2429902176
- https://github.com/package-url/purl-spec/pull/176#issuecomment-2429913910

**Comment by johnmhoran** [comment]
These comments also assert that Go PURLs correctly interpret the entire encoded block as the name and note that Go does not have the concept of a namespace.
