### ISSUE TITLE
No support of python version as mentioned in documentation

### ISSUE THREAD

**Issue by Samk1710** [aboutcode-org/vulnerablecode#1624]
While installing vulnerable code, I faced certain issues related to versions of python.
In the documentation, the pre-installation checklist provides Python 3.8+, but  python 3.12.6  throws errors.

For python 3.12,
The document uploaded contains the terminal output.

In a gist,

ERROR:
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'? make: *** [Makefile:55: dev] Error 1

REASON:
Module 'pkgutil' has no attribute 'ImpImporter' occurs because the ImpImporter attribute was deprecated and removed in Python 3.3, and now replaced by zipimporter.

https://gist.github.com/Samk1710/3bab7f71a471f127386d11ed3c212194

[vulcodeissue1.docx](https://github.com/user-attachments/files/17440798/vulcodeissue1.docx)

**Comment by Hritik14** [comment]
looks like a breaking change in pip. can you try this https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean
