### ISSUE TITLE
ERROR during installation

### ISSUE THREAD

**Issue by Samk1710** [aboutcode-org/vulnerablecode#1626]
I am currently facing this issue while installing  vulnerable code in my system locally. My system has python 3.9.18 ,  git version 2.45.2 and psql (PostgreSQL) 16.4 (Debian 16.4-1). This is following the both the github and documentation guidelines.

I have attached the screenshots.

![ss1](https://github.com/user-attachments/assets/49d853dc-0e8c-4cfe-8c4c-c68b1f9e02fb)

![ss2](https://github.com/user-attachments/assets/4d8ac512-f95d-406b-8b82-69563f2f21e1)

**Comment by Hritik14** [comment]
You already have an env file. You can just do
``make dev postgres`` no need of envfile

also, please refrain from image screenshots. you can upload logs to gist or similar
