### ISSUE TITLE
Migrate pysec importer to aboutcode pipeline

### ISSUE THREAD

**Issue by keshav-space** [aboutcode-org/vulnerablecode#1627]

**Comment by pombredanne** [comment]
Thanks for completing this!
Can you explain with a few words how to use this new pipeline?

**Comment by keshav-space** [comment]
Completed in https://github.com/aboutcode-org/vulnerablecode/pull/1628

The simple way to test this is to follow the below steps after installing VulnerableCode (https://github.com/aboutcode-org/vulnerablecode?tab=readme-ov-file#getting-started):

- Run this command to collect the pysec advisories:
    ```
    python manage.py import pysec_importer
    ```
