### ISSUE TITLE
Reset default VCIO API to v1 and announce availability of v2

### ISSUE THREAD

**Issue by mjherzog** [aboutcode-org/vulnerablecode#1663]
Sometime last week the default API for VCIO changed to v2 without any announcement of the change or how v2 is different.

When you select API from the top menu and click on the [VulnerableCode JSON REST API](https://public.vulnerablecode.io/api/v2/) link you are sent to:

https://public.vulnerablecode.io/api/v2/ shows:
The default basic root view for DefaultRouter
GET /api/v2/

You can apparently get to the old API by removing /v2/ from the URL - https://public.vulnerablecode.io/api/ shows:
The default basic root view for DefaultRouter
GET /api/

This is very confusing. I do not see any documentation at: https://vulnerablecode.readthedocs.io/en/latest/api.html about the v2 API and how it is different from v1.

Longer term we probably need something like the DejaCode dropdown menu, but in the short term perhaps we could add a one-time menu item for the v2 API to alert users about the change. And obviously we need documentation of v2 and the differences from v1 in ReadTheDocs.

**Comment by TG1999** [comment]
@mjherzog ack! good catch
