### ISSUE TITLE
Missing summary in https://public.vulnerablecode.io/vulnerabilities/VCID-jaz4-2j4u-aaas

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/vulnerablecode#1684]
We have a missing summary in https://public.vulnerablecode.io/vulnerabilities/VCID-jaz4-2j4u-aaas

**Comment by DennisClark** [comment]
@pombredanne   there are lots of missing summaries in the VCIO data.  If there should always be one, I think we probably need to do a mass data cleanup.

**Comment by pombredanne** [comment]
Closed as duplicate of https://github.com/aboutcode-org/vulnerablecode/issues/1684
