### ISSUE TITLE
manage.py import should provide some kind of progress feedback

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/vulnerablecode#318]
Right now we do not know what happens and what was done.
Design TBD

**Comment by AmitGupta7580** [comment]
I added progress bar in NVD importer . Using `tqdm` package

![image](https://user-images.githubusercontent.com/57043342/113254007-a8134a00-92e3-11eb-895d-86be0762fc32.png)

**Comment by AmitGupta7580** [comment]
I face some problems while adding progress bar in other importers. 
As you know data is importing in 2 different processes.

1. Downloading data from resources and cast into Advisory class.
2. Adding advisory to postgresql database.

Some importers do these task at same time e.g : NVD
While other importers first collect all the data then save it to database e.g : archlinux

[Solution] To add a common progress bar we has to implement all importers in similar fashion.

**Comment by Hritik14** [comment]
> Eventually we want to move to non-batch proccessing
I think this can be better done after https://github.com/nexB/vulnerablecode/issues/338

**Comment by unibik** [comment]
Hi! I was looking this issue#318 and was wondering if it is still open or if it has already been resolved. If it's still open, I'd be happy to work on it. Please let me know. Thank you!

**Comment by pombredanne** [comment]
As @keshav-space pointed to, we are moving to all-background importer and improvers running as pipelines.

Therefore a command line progress bar does not make sense in the general case.

What we need instead is something the same as ScanCode.io loop progress https://github.com/aboutcode-org/scancode.io/blob/e1607c7f9684dbca9cf67bbbbf3145e0aaf06fdf/aboutcode/pipeline/__init__.py#L260 and this is now part of https://pypi.org/project/aboutcode.pipeline/ which we have already in VCIO and all the new pipelines are using this progress indicator.

I am closing this as completed.

**Comment by pombredanne** [comment]
The main issue for pipelines is:
- https://github.com/aboutcode-org/vulnerablecode/issues/1509
