### ISSUE TITLE
Add Improver to find out Ghost packages

### ISSUE THREAD

**Issue by TG1999** [aboutcode-org/vulnerablecode#917]
We have some packages coming from security advisories that doesn't exist anywhere, we should have an improver to verify if a package actually exists.

See also:
- https://github.com/nexB/vulnerablecode/issues/644
- https://github.com/nexB/vulnerablecode/issues/1144

**Comment by armijnhemel** [comment]
Would this be an improver per data source or a generic improver covering all data sources? Take for example #915, it could be an improver looking at (historical) package information from Alpine and specifically for Alpine.

**Comment by sify21** [comment]
Add an example for rust:

**Comment by keshav-space** [comment]
Some of these non-existent packages could be the result of incorrect parsing of version ranges from upstream advisories https://github.com/nexB/vulnerablecode/issues/1516.
