### ISSUE TITLE
Make models better for efficient queries

### ISSUE THREAD

**Issue by TG1999** [aboutcode-org/vulnerablecode#966]
Currently we store packagerelatedvulnerabilities in one table, either a package fixes a vulnerability or affected by some vulnerability, the combination of package and vulnerability is stored in the same table with a flag for fix, We should segregate this data in 2 tables. 

See also:
- https://github.com/nexB/vulnerablecode/issues/595
- https://github.com/nexB/vulnerablecode/issues/1549

**Comment by pombredanne** [comment]
Here are the diagrams we discussed in today's community call:

![models](https://github.com/user-attachments/assets/6b73b79a-51e5-4465-bfd3-a075a54e40ff)
